import {escapeHtml as esc} from '/shared/render.js';

export async function openBackups(api) {
  let dialog=document.querySelector('#backups-dialog');
  if(!dialog){dialog=document.createElement('dialog');dialog.id='backups-dialog';document.body.append(dialog);}
  const sections=[{kind:'portfolio',title:'Portfolio snapshots',description:'The installer automatically saves and verifies your portfolio, original images and settings before upgrading. Snapshots stay on this computer; they do not protect against disk failure. Windows-encrypted credentials require the same Windows user to recover.',items:'portfolioItems',keep:'portfolioKeep'},{kind:'code',title:'Code backups',description:'Earlier application versions saved by the updater. These do not contain your portfolio, artwork or credentials.',items:'items',keep:'keep'}];
  dialog.innerHTML='<div class="dialog-heading"><h2>Backups</h2><button aria-label="Close">×</button></div><p class="muted">Removed backups go to the Windows Recycle Bin. Failed upgrades retain their recovery backups. Applying retention also removes existing backups beyond the chosen limit.</p>'+sections.map(section=>`<section data-backup-kind="${section.kind}"><h3>${section.title}</h3><p>${section.description}</p><label>After a successful upgrade<select><option value="1">Keep the latest (default)</option><option value="3">Keep the latest three</option><option value="-1">Keep all</option><option value="0">Remove all after a successful upgrade</option></select></label><button data-apply>Apply retention</button><div data-list></div></section>`).join('')+'<p id="backup-status" role="status"></p>';
  dialog.querySelector('[aria-label="Close"]').onclick=()=>dialog.close();
  const status=dialog.querySelector('#backup-status');
  async function refresh(){const result=await api('backups');for(const section of sections){const panel=dialog.querySelector(`[data-backup-kind="${section.kind}"]`);panel.querySelector('select').value=String(result[section.keep]);const list=panel.querySelector('[data-list]');list.innerHTML=(result[section.items]||[]).map(item=>`<article class="backup-row"><p><strong>Version ${esc(item.version)}</strong> · ${esc(item.id)} · ${(item.bytes/1048576).toFixed(2)} MB</p><button data-reveal="${esc(item.id)}">Show in File Explorer</button> <button data-remove="${esc(item.id)}">Remove backup</button></article>`).join('')||'<p>No backups stored.</p>';
    list.querySelectorAll('[data-reveal]').forEach(button=>button.onclick=()=>action('reveal',{kind:section.kind,id:button.dataset.reveal}));
    list.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{if(button.dataset.confirmed!=='yes'){button.dataset.confirmed='yes';button.textContent='Confirm removal';return;}action('delete',{kind:section.kind,id:button.dataset.remove});});
  }}
  async function action(name,body){dialog.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await api('backups/'+name,body);await refresh();status.textContent=result.recoveryFolders?.length?'Removed from the list. Recovery copy retained at '+result.recoveryFolders.join(', '):name==='reveal'?'Opened in File Explorer.':name==='settings'?'Retention saved. Older backups sent to the Recycle Bin.':'Backup sent to the Recycle Bin.';}catch(error){status.textContent=error.message;}finally{dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  for(const section of sections){const panel=dialog.querySelector(`[data-backup-kind="${section.kind}"]`);panel.querySelector('[data-apply]').onclick=()=>action('settings',{kind:section.kind,keep:Number(panel.querySelector('select').value)});}
  dialog.showModal();try{await refresh();}catch(error){status.textContent=error.message;}
}
